testing

diff --git a/bashcrypto b/bashcrypto
--- a/bashcrypto
+++ b/bashcrypto
@@ -54,13 +54,6 @@ function encrypt() {
     fi
     echo -e $okegreen
     echo "[+] Done!"
-    echo "[?] delete plain file? (y/n)"
-    read answer
-    if [[ $answer == "y" ]]; then
-        rm $INPUT_FILE
-        echo "[!] deleted inputfile!"
-    fi
-    echo ""
 }
 
 function decrypt() {
@@ -99,18 +92,20 @@ while getopts "edi:o:p:Hh" opt;do
     i)
         INPUT_FILE=$OPTARG
         if [[ -f $INPUT_FILE ]] ; then
-            echo -e $okgreen
-            echo "[+] inputfile found!"
-            echo ""
+		echo -e $okgreen
+            	echo "[+] inputfile found!"
+            	echo ""
         elif [[ -d $INPUT_FILE ]] ; then
-            echo -e $okgreen
-            echo "[+] directory found!"
-            echo ""
+
+        	echo -e $okgreen
+            	echo "[+] directory found!"
+            	echo ""
+		DIRMODE=1
         else
-            echo -e $red
-            echo "[!] INPUT NOT FOUND!"
-            exit 1
-            echo ""
+            	echo -e $red
+            	echo "[!] INPUT NOT FOUND!"
+            	exit 1
+            	echo ""
         fi
         ;;
     e)
